Adds location reminder field in Task class
steroid-team/app pull request #247
Opened 2021-05-13 12:58 UTC by sydneyhauke

Addresses #227.

For now it justs adds a (nullable) Location field in the Task class.

I would like your input on what I could further add.

2021-05-13 15:49 UTC, YagoGG requested changes
Hey, @sydneyhauke! Thanks a bunch for this.

I am missing a method (see inline comment), as well as the corresponding modifications to the `JSONSerializerTest`. See #249 for context, and #212 as an example.

Cheers!

2021-05-13 15:49 UTC, YagoGG commented on app/src/main/java/com/github/steroidteam/todolist/model/todo/Task.java
> +        Objects.requireNonNull(location);
If we add this condition (which I think is good, just like we do with due dates), we need another method to remove the location reminder. See `Task.removeDueDate` for reference.

2021-05-20 13:25 UTC, sydneyhauke commented
Ok, so I decided to use this already existing branch for issue #247. Now it it possible to add a location reminder in a task by pinpointing on a map. The location remains persistent in the database.

2021-05-20 13:25 UTC, sydneyhauke commented
Ok, so I decided to use this already existing branch for issue #247. Now it it possible to add a location reminder in a task by pinpointing on a map. The location remains persistent in the database.

2021-05-20 20:45 UTC, theo-damiani approved these changes
Nice PR, very good work!

For me, we can merge it, maybe just remove the TodoReposiroty and ItemViewModel file.

2021-05-20 22:32 UTC, YagoGG approved these changes
Thanks a lot for the work, @sydneyhauke!

![ship it!](https://media1.tenor.com/images/1f580aefc14b6320e13b0f94f0f7b687/tenor.gif?itemid=4770652)

2021-05-21 07:29 UTC, merged