User and Credits
steroid-team/app pull request #317
Opened 2021-06-04 17:13 UTC by theo-damiani

2021-06-04 19:32 UTC, YagoGG requested changes
Hey @theo-damiani! Thanks for the changes, I left a few minor inline comments.

I am a bit confused as to why the user has to re-authenticate. Is it an intentional security feature? For what I saw in the code, it does not seem to be required by Firebase (but I might have misunderstood it).

2021-06-04 19:32 UTC, YagoGG commented on app/src/main/java/com/github/steroidteam/todolist/viewmodel/UserViewModel.java
> +        System.err.println("ON LOAD !!!!!!!!!!!!!!!!! <<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
Debug statement, should be removed.

2021-06-04 19:32 UTC, YagoGG commented on app/src/main/java/com/github/steroidteam/todolist/viewmodel/UserViewModel.java
> +                                System.out.println("=================================>");
Debug statement, should be removed.

2021-06-04 19:32 UTC, YagoGG commented on app/src/main/res/layout/fragment_profile.xml
> +                android:text="Modify password:" />
Unwanted colon (`:`) at the end.

2021-06-04 19:32 UTC, YagoGG commented on app/src/main/java/com/github/steroidteam/todolist/view/dialog/AuthDialogFragment.java
> +    private final String DIALOG_TITLE = "Please, you need to re-authenticate!";
Move this to `strings.xml` and then do `R.strings.X`.

2021-06-04 21:23 UTC, YagoGG approved these changes
Made the changes with Théo, it looks great(er) now. Cheers!

2021-06-07 21:43 UTC, VPellenc approved these changes
It works very well, thanks for the feature!

2021-06-07 21:44 UTC, merged