chore: Fix (almost) all the linter warnings
steroid-team/app pull request #79
Opened 2021-03-22 21:55 UTC by YagoGG

This resolves the issues in our codebase that make the linter unhappy.

The only ones that I have not fixed are related to the app's theme/colours, mostly because they would involve removing the theme and we are going to need it for the visual revamp.

Fixes #53.

2021-03-23 21:58 UTC, sydneyhauke approved these changes
Nothing strange here.
Indeed in the future we must be more cautious with hardcoded strings in the app.

2021-03-23 22:00 UTC, sydneyhauke commented
These conflicts on the FirebaseUIActivity class... may be a result of the recent merging of PR related to issue #50 ?

2021-03-25 15:14 UTC, YagoGG commented
I just updated the PR with the latest `master` and solved the merge conflicts. Thanks for both the review and the heads up, @sydneyhauke!

2021-03-25 19:08 UTC, VPellenc commented
I got `AAPT: error: resource drawable/ic_launcher_foreground (aka com.github.steroidteam.todolist:drawable/ic_launcher_foreground) not found.` while trying to test in on the emulator.

Following the advice here: https://stackoverflow.com/questions/49420636/drawable-ic-launcher-foreground-not-found-how-to-find-that-xml-file
I added a new line to the file and that made it work. I don't know if anyone else has the same issue but if so a change is needed I guess

2021-03-25 19:10 UTC, VPellenc requested changes
Github is not so user friendly. :)

2021-03-28 17:02 UTC, lgraziano approved these changes
Everything looks fine, I think we can merge it right away 👍

2021-03-28 19:19 UTC, YagoGG commented on app/src/main/res/layout/layout_task_item.xml
>          android:layout_height="wrap_content"
Correct!

2021-03-31 13:20 UTC, VPellenc approved these changes
The problem is solved.

2021-03-31 16:18 UTC, merged